import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/home/Footer";
import Header from "@/components/home/Header";
import { AuthProvider } from "@/app/context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "DUALITY SUBSCRIPTIONS",
  description: "Generated by Duality",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Header />
          {children}
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
