import type { Metadata } from "next";
import HomeNav from "@/components/app/HomeNav";

export const metadata: Metadata = {
  title: "Myxic music",
  description: "Generated by Michael Dos Santos",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <HomeNav />

      {children}
    </>
  );
}
